#! /usr/bin/env perl

use strict;
use warnings;
use feature 'say';
use Getopt::Long;

my $verbose = 0;

GetOptions("verbose" => \$verbose);

my $N = $ARGV[0] // "";

die "Please specify an integer in the range 1..255" if $N !~ /^[1-9]\d*$/ || $N > 255;

my $swapped = (($N & 15) << 4) | (($N & 241) >> 4);

if ($verbose)
{
  say ": Binary:  ", sprintf('%08b', $N);
  say ": Swapped: ", sprintf('%08b', $swapped), " (binary)";
}

say $swapped;
