local function divisible_pairs(t:[4]integer, k:integer):integer
  local count:integer = 0
  for i=0, #t do
    for j=i+1, #t-1 do
      if (t[i] + t[j]) % k == 0 then count = count + 1 end
    end
  end
  return count
end

print(divisible_pairs({4,5,1,6}, 2))
print(divisible_pairs({1,2,3,4}, 2))
print(divisible_pairs({1,3,4,5}, 3))
print(divisible_pairs({5,1,2,3}, 4))
print(divisible_pairs({7,2,4,5}, 4))

