#!/usr/bin/env perl

use strict;
use warnings;
use Test::More;

is `gforth ch-1.fth \\
GTAAACCCCTTTTCATTTAGACAGATCGACTCCTTATCCATTCTCAGAGATGTGTTGCTGGTCGCCG`, <<'END';
67 
CATTTGGGGAAAAGTAAATCTGTCTAGCTGAGGAATAGGTAAGAGTCTCTACACAACGACCAGCGGC
END

is `gforth -e '14 12' ch-2.fth`, "168 \n";

done_testing;
