=pod

=encoding utf8

=head1 #1 Perfect numbers

=over 4

Write a script that computes the first five perfect numbers. A perfect number is
an integer that is the sum of its positive proper divisors (all divisors except
itself). Please check L<Wiki|https://en.wikipedia.org/wiki/Perfect_number> for
more information. This challenge was proposed by Laurent Rosenfeld.

=back

Mine is a straightforward implementation of the naive solution. But it's very
inefficient. On my computer it takes about two seconds to print the first four
perfect numbers (6, 28, 496, and 8128). However, I didn't have the patience to
wait for it to print the fifth number, as it's very large and the time
complexity of the algorithm that checks if a number is perfect is linear (O(n))
on the number size.

=head1 #2 Center lines

=over 4

Write a function, ‘center’, whose argument is a list of strings, which will be
lines of text. The function should insert spaces at the beginning of the lines
of text so that if they were printed, the text would be centered, and return the
modified lines.

=back

This is a simple problem with a simple solution which I implemented in a three
line long function.

The script reads lines from STDIN or from the files passed to it as arguments
and invokes the C<center> function for all the lines, printing them centered.
