# Pad link: 
# https://www.uiua.org/pad?src=0_8_0__U3BsaXRTdHJpbmdzIOKGkCAv4oqU4oqC4omhKOKWoeKKnOKWoeKKlCjiiaAsKSkKCi0tLQoiLiIgeyJvbmUudHdvLnRocmVlIiAiZm91ci5maXZlIiAic2l4In0K4o2k4oqD4ouF4oiY4omNIHsib25lIiAidHdvIiAidGhyZWUiICJmb3VyIiAiZml2ZSIgInNpeCJ9IFNwbGl0U3RyaW5ncwoKIiQiIHsiJHBlcmwkJCIgIiQkcmFrdSQifQrijaTiioPii4XiiJjiiY0geyJwZXJsIiAicmFrdSJ9IFNwbGl0U3RyaW5ncwotLS0K

SplitStrings ← /⊔⊂≡(□⊜□⊔(≠,))

---
"." {"one.two.three" "four.five" "six"}
⍤⊃⋅∘≍ {"one" "two" "three" "four" "five" "six"} SplitStrings

"$" {"$perl$$" "$$raku$"}
⍤⊃⋅∘≍ {"perl" "raku"} SplitStrings
---
