# Pad link:
# https://www.uiua.org/pad?src=0_8_0__V2Vha2VzdFJvdyDihpAg4o2P4omhLysKCi0tLQpbMV8xXzBfMF8wCiAxXzFfMV8xXzAKIDFfMF8wXzBfMAogMV8xXzBfMF8wCiAxXzFfMV8xXzFdCgrijaTiioPii4XiiJjiiY0gWzIgMCAzIDEgNF0gV2Vha2VzdFJvdwoKWzFfMF8wXzAKIDFfMV8xXzEKIDFfMF8wXzAKIDFfMF8wXzBdCuKNpOKKg-KLheKImOKJjSBbMCAyIDMgMV0gV2Vha2VzdFJvdwotLS0K

WeakestRow ← ⍏≡/+

---
[1_1_0_0_0
 1_1_1_1_0
 1_0_0_0_0
 1_1_0_0_0
 1_1_1_1_1]

⍤⊃⋅∘≍ [2 0 3 1 4] WeakestRow

[1_0_0_0
 1_1_1_1
 1_0_0_0
 1_0_0_0]
⍤⊃⋅∘≍ [0 2 3 1] WeakestRow
---
