#! /usr/bin/env perl

use strict;
use warnings;
use feature 'say';
use feature 'signatures';

no warnings qw(experimental::signatures);

my $verbose = 0;

my $N = shift(@ARGV);

die "Specify a positive integer with at least two digits"
  unless $N =~ /^[1-9]\d+$/;

my @result;

get_val(undef, $N);

sub get_val ($done, $todo)
{
  my @done = $done ? @$done : ();
  for my $size (1 .. length($todo))
  {
    my @done2 = @done;
    my $val   = substr($todo, 0, $size);
    my $todo2 = substr($todo, $size);
      
    push(@done2, $val);

    length($todo2)
      ? get_val(\@done2, $todo2)
      : push(@result, \@done2);
  }
}

for my $res (@result)
{
  say join(",", @$res);
}
