#!/usr/local/bin/perl

use strict;

use warnings;
use feature qw(say);
use Test::More;

## Generate the list of self descritpive numbers for base
## < 7 - these are the ones that don't! follow the rules..
## All other numbers can be generated by the rule
## n-4, 2, 1, 0 (n-7 times), 1, 0, 0, 0

my ($c,@res) = 0;
while( ++$c && @res<3 ) {
  push @res, $c if $c == join q(),
    map { scalar @{[ $c=~m{($_)}g ]} } 0 .. -1 + length $c;
}

say "@res";

