# 12x12 Soduko (sudoku-download.net)
 D  C  F  I  H  E  L  J  K  B  A  G
 H  A  J  B  G  K  D  C  F  L  E  I
 L  G  E  K  F  I  B  A  C  H  D  J
 A  E  I  H  L  F  J  B  D  G  C  K
 F  D  B  L  K  C  I  G  H  A  J  E
 C  J  K  G  E  D  A  H  L  I  B  F
 I  B  C  A  J  L  H  E  G  F  K  D
 E  H  D  F  A  G  K  I  J  C  L  B
 K  L  G  J  C  B  F  D  I  E  H  A
 J  I  H  D  B  A  C  F  E  K  G  L
 G  K  A  C  I  J  E  L  B  D  F  H
 B  F  L  E  D  H  G  K  A  J  I  C
