#! /usr/bin/env perl

use strict;
use warnings;
use feature 'say';
use Math::BigInt::Named;

my $limit = int($ARGV[0] || 100);

my @numbers;

for my $candidate (1 .. $limit)
{
  push(@numbers, $candidate) unless Math::BigInt::Named->new($candidate)->name =~ /e/;
}

say join(", ", @numbers);
