#!/usr/bin/env perl
# vim:set ts=4 sw=4 sts=4 et ai wm=0 nu:
#=============================================================================
# Copyright (c) 2026, Bob Lied
#=============================================================================
# ch-1.pl Perl Weekly Challenge 382 Task 1  Mamiltonian Cycle
#=============================================================================
# You are given a target number.  Write a script to arrange all the whole
# numbers from 1 up to the given target number into a circle so that every
# pair of side-by-side numbers adds up to a perfect square. Please make sure,
# the last number and the first must also add up to a square.
# Example 1 Input: $n = 32
#           Output: 1, 8, 28, 21, 4, 32, 17, 19, 30, 6, 3, 13,
#           12, 24, 25, 11, 5, 31, 18, 7, 29, 20, 16, 9, 27,
#           22, 14, 2, 23, 26, 10, 15
#    1  + 8  = 9     8 + 28 = 36    28 + 21 = 49    21 + 4  = 25
#   4  + 32 = 36    32 + 17 = 49    17 + 19 = 36    19 + 30 = 49
#   so on, all the way through the sequence.
#
# Example 2 Input: $n = 15
#           Output: () No valid circular list of numbers exists.
#
# Example 3 Input: $n = 34
#       Output: 1, 8, 28, 21, 4, 32, 17, 19, 6, 30, 34, 15,
#              10, 26, 23, 2, 14, 22, 27, 9, 16, 33, 31, 18,
#              7, 29, 20, 5, 11, 25, 24, 12, 13, 3
#=============================================================================

use v5.42;

use Getopt::Long;
my $Verbose = false;
my $DoTest  = false;
my $Benchmark = 0;

GetOptions("test" => \$DoTest, "verbose" => \$Verbose, "benchmark:i" => \$Benchmark);
my $logger;
{
    use Log::Log4perl qw(:easy);
    Log::Log4perl->easy_init({ level => ($Verbose ? $DEBUG : $INFO ),
            layout => "%d{HH:mm:ss.SSS} %p{1} %m%n" });
    $logger = Log::Log4perl->get_logger();
}
#=============================================================================

exit(!runTest()) if $DoTest;
exit( runBenchmark($Benchmark) ) if $Benchmark;

say join(", ", task($_)->@*) for @ARGV;

#=============================================================================
sub task($n)
{
    use List::AllUtils qw/any first_index/;
    # All the squares that might be sums of the available numbers.
    state @Square = map { $_*$_ } 2 .. floor(sqrt(2*$n - 1));

    my @queue = ( [ [1], [ 2 .. $n] ] );

    my @cycle = ();
    while ( @queue )
    {
        my ($sequence, $available) = shift(@queue)->@*;
        if ( @$available == 0 )
        {
            if ( any { $_ == $sequence->[0] + $sequence->[-1] } @Square )
            {
                push @cycle, $sequence;
            }
            else { next; }
        }

        my $j = $sequence->[-1];
        for my $sq ( grep { $_ > $j } @Square )
        {
            my $diff = $sq - $j;
            if ( (my $which = first_index { $_ == $diff } $available->@*) >= 0 )
            {
                my @avail = $available->@[0..$which-1, $which+1 .. $available->$#*];
                push @queue, [ [ $sequence->@*, $diff ], [ @avail ] ];
            }
        }
    }
    return \@cycle;
}

sub runTest
{
    use Test2::V1 -ipP;

    is( task(32), [ 1, 8, 28, 21, 4, 32, 17, 19, 30, 6, 3, 13,
                    12, 24, 25, 11, 5, 31, 18, 7, 29, 20, 16, 9, 27,
                    22, 14, 2, 23, 26, 10, 15 ], "Example 1");
    is( task(15), [], "Example 2");
    is( task(34), [ 1, 8, 28, 21, 4, 32, 17, 19, 6, 30, 34, 15,
                    10, 26, 23, 2, 14, 22, 27, 9, 16, 33, 31, 18,
                    7, 29, 20, 5, 11, 25, 24, 12, 13, 3 ], "Example 3");

    done_testing;
}

sub runBenchmark($repeat)
{
    use Benchmark qw/cmpthese/;

    cmpthese($repeat, {
            label => sub { },
        });
}
