#!/usr/bin/env perl
# vim:set ts=4 sw=4 sts=4 et ai wm=0 nu:
#=============================================================================
# Copyright (c) 2026, Bob Lied
#=============================================================================
# ch-2.pl Perl Weekly Challenge 364 Task 2  Goal Parser
#=============================================================================
# You are given a string, $str. Write a script to interpret the given string
# using Goal Parser. The Goal Parser interprets “G” as the string “G”, “()”
# as the string “o”, and “(al)” as the string “al”. The interpreted strings
# are then concatenated in the original order.
# Example 1 Input: $str = "G()(al)"
#           Output: "Goal"
# Example 2 Input: $str = "G()()()()(al)"
#           Output: "Gooooal"
# Example 3 Input: $str = "(al)G(al)()()"
#           Output: "alGaloo"
# Example 4 Input: $str = "()G()G"
#           Output: "oGoG"
# Example 5 Input: $str = "(al)(al)G()()"
#           Output: "alalGoo"
#=============================================================================

use v5.42;


use Getopt::Long;
my $Verbose = false;
my $DoTest  = false;
my $Benchmark = 0;

GetOptions("test" => \$DoTest, "verbose" => \$Verbose, "benchmark:i" => \$Benchmark);
my $logger;
{
    use Log::Log4perl qw(:easy);
    Log::Log4perl->easy_init({ level => ($Verbose ? $DEBUG : $INFO ),
            layout => "%d{HH:mm:ss.SSS} %p{1} %m%n" });
    $logger = Log::Log4perl->get_logger();
}

#=============================================================================
    my @version = ( { name => "regex s///", code => \&parse },
                    { name => "map join  ", code => \&parseMAP },
    );
#=============================================================================

exit(!runTest()) if $DoTest;
exit( runBenchmark($Benchmark) ) if $Benchmark;

say parse($_) for @ARGV;

#=============================================================================
sub parse($str)
{
    state %replace = ( G => "G", "()" => "o", "(al)" => "al" );
    $str =~ s/(G|\(\)|\(al\))/$replace{$1}/erg;
}

sub parseMAP($str)
{
    state %replace = ( G => "G", "()" => "o", "(al)" => "al" );
    join "", map { $replace{$_} } $str =~ m/(G|\(\)|\(al\))/g
}

sub parseSTR($str)
{
    my $state = my $result = "";

    for my $c ( split(//, $str) )
    {
        if ( state eq "ERROR" ) { return $str }
        if ( state eq "START" )
        {
            if    ( $c eq "G" ) { $result .= "G" }
            elsif ( $c eq "(" ) { $state = "OPEN" }
            elsif ( $c eq ")" ) { $state = "ERROR" }
            elsif ( $c eq "a" ) { $state = "ERROR" }
            elsif ( $c eq "l" ) { $state = "ERROR" }
        }
        if ( state eq "OPEN" )
        {
            if    ( $c eq "G" ) { $result .= "G" }
            elsif ( $c eq "(" ) { $state = "OPEN" }
            elsif ( $c eq ")" ) { $state = "ERROR" }
            elsif ( $c eq "a" ) { $state = "ERROR" }
            elsif ( $c eq "l" ) { $state = "ERROR" }
        }

    }

    return $result;
}

sub runTest
{
    use Test2::V0;
    my @case = (
    { input => "G()(al)" ,       expect => "Goal",    desc => "Example 1" },
    { input => "G()()()()(al)" , expect => "Gooooal", desc => "Example 2" },
    { input => "(al)G(al)()()" , expect => "alGaloo", desc => "Example 3" },
    { input => "()G()G" ,        expect => "oGoG",    desc => "Example 4" },
    { input => "(al)(al)G()()" , expect => "alalGoo", desc => "Example 5" },
    );

    for my $sub ( @version )
    {
        for my $c ( @case )
        {
            is( $sub->{code}( $c->{input} ), $c->{expect}, "$sub->{name} $c->{desc}" );
        }
    }

    done_testing;
}

sub runBenchmark($repeat)
{
    use Benchmark qw/cmpthese/;

    cmpthese($repeat, {
            label => sub { },
        });
}
