#! /usr/bin/env perl

use strict;
use List::Util;
use feature 'say';

my $input = shift(@ARGV) || die "Please specify a matrix";

my @old;
my @new;

my $cols;
my $rows = 0;

for my $row (split(/\[/, $input))
{
  next unless $row;
  $row =~ tr/\]//d;
  $row = $1 if $row =~ /^\s*(.*?)\s*$/;
  my @values = split(/\s+/, $row);

  die "Only '0' and '1' please" unless List::Util::all { $_ eq "0" || $_ eq "1" } @values;

  if (defined $cols)
  {
    die "Not the same number of elements in all the rows" unless $cols == @values;
  }
  else
  {
    $cols = @values;
  }

  my @copy = @values;    # As we use a reference in the «push».
  
  push(@old, \@values);
  push(@new, \@copy);
  $rows++;
}

for my $row (0 .. $rows -1)
{
  for my $col (0 .. $cols -1)
  {      
    if ($old[$row][$col] == 0)
    {
      for my $a (0 .. $rows-1)
      {
        $new[$row][$a] = 0;
      }
      
      for my $b (0 .. $cols-1)
      {
	$new[$b][$col] = 0;
      }
    }
  }
}

for my $row (0 .. $rows -1)
{
  my @values = ();
  for my $col (0 .. $cols -1)
  {
    push(@values, $new[$row][$col]);
  }
  say "[", join(", ", @values), "]";
}
