all: brainfuck/ch-1.bf brainfuck/ch-2.bf
	perl ../../challenge-001/paulo-custodio/test.pl

brainfuck/ch-1.bf: brainfuck/ch-1.pl
	perl brainfuck/ch-1.pl > $@

brainfuck/ch-2.bf: brainfuck/ch-2.pl
	perl brainfuck/ch-2.pl > $@
