package ringlet:pwc315-t2-find-third@0.1.0;

interface find-third {
    find-third: func(sentence: string, wfirst: string, wsecond: string) -> list<string>;
}

world pwc315-t2-find-third {
    export find-third;
}
