#! /usr/bin/env perl

use strict;
use warnings;
use feature 'say';
use Getopt::Long;

my $verbose = 0;

GetOptions("verbose" => \$verbose);

my $s    = $ARGV[0];
my @s    = split(//, $s);
my %freq;

for my $char (@s)
{
  $freq{$char}++;
}

for my $index (0 .. @s -1)
{
  my $char  = $s[$index];
  my $count = $freq{$char};

  say ": Char $char with frequency $count" if $verbose;

  if ($count == 1)
  {
    say $index;
    last;
  }
}
