[package]
name = "challenge-238"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ch-1"
path = "src/ch-1.rs"

[[bin]]
name = "ch-2"
path = "src/ch-2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7"
