#! /usr/bin/env perl

use strict;
use feature 'say';

use Getopt::Long;
use Math::Prime::Util 'factor';
# use List::MoreUtils 'duplicates';

my $verbose = 0;

GetOptions("verbose"  => \$verbose);

my $N = $ARGV[0] // die "Please specify a number";

my @factors  = factor($ARGV[0]);
my @repeated = duplicates(@factors);

if ($verbose)
{
  say ": Factors: ",  join(", ", @factors);
  say ": Repeated: ", join(", ", @repeated);
}

say @repeated ? 1 : 0;

sub duplicates (@)
{
    my %seen = ();
    my $k;
    my $seen_undef;
    return grep { 1 < (defined $_ ? $seen{$k = $_} : $seen_undef) }
      grep { defined $_ ? not $seen{$k = $_}++ : not $seen_undef++ } @_;
}
