#! /usr/bin/env perl

use strict;
use warnings;
use feature 'say';

my $N = $ARGV[0] // die "Please specify a positive integer";
die "Please specify a positive integer" unless $N =~ /^[1-9]\d*$/;

my $count = 0;

/1/ ? () : $count++ for (2 .. $N);

say $count;

