#! /usr/bin/env perl

use strict;
use warnings;
use feature 'say';
use feature 'signatures';

no warnings qw(experimental::signatures);

my $N = shift(@ARGV) || "";

die "Please specify a positive integer" unless $N =~ /^[1-9]\d*$/;

say look_and_say($N);

sub look_and_say ($input)
{
  $input =~ s/((.)\2*)/length($1) . $2/ge;
  
  return $input;
}

