# Task 1 of the Weekly Challenge 356
# https://theweeklychallenge.org/blog/perl-weekly-challenge-356/#TASK1

# Test run:
# % raku ch-1.raku
# 2
# 3
# 3
# 4
# 4

sub count-ones($n) {
    ($n.comb.grep: '1').elems
}

sub kolakoski(Int $n where * > 3) { # This function mostly generated by ChatGPT
    my @seq = 1, 2, 2;
    my $i = 2;          # index into the sequence for run lengths
    my $value = 1;      # next value to append

    while @seq.elems < $n {
        my $count = @seq[$i++];
        @seq.push: |($value xx $count);  # to make it flat
        $value = $value == 1 ?? 2 !! 1;  # alternate between 1 and 2
    }

    @seq[0 ..^ $n]
}

say count-ones(kolakoski(4));
say count-ones(kolakoski(5));
say count-ones(kolakoski(6));
say count-ones(kolakoski(7));
say count-ones(kolakoski(8));
