# gh workflow run 'manual raku benchmark run' --ref branch-name -f week=DEMO
# gh workflow run 'manual raku benchmark run' --ref branch-name -f week=nr234

name: manual raku benchmark run

on:
  #push: # if workflow is not appearing on branch, run with push: instead of workflow_dispatch: once
  workflow_dispatch:
    inputs:
      week:
        description: 'weekly challenge nr to run benchmark on - like nr234'
        default: 'DEMO'
        required: true
        type: string

jobs:
  raku-benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Status
      run: echo "Processing week ${{ inputs.week }}"
    - name: Update apt
      run: sudo apt-get update
    - name: Install Rakudo
      run: sudo apt-get install rakudo
    - name: Check Raku version
      run: raku --version
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run Benchmark # will crash when run without sudo - that should be fixed somehow! https://github.com/rakudo/star/issues/192
      run: sudo raku --optimize=3 -I challenge-${{ inputs.week }} -- test/benchmark-scalabiity.raku --out-folder=/tmp --v=True --max-run-times=1,2,3 ${{ inputs.week }}
    - name: Archive benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: scalability-benchmark-data
        path: /tmp/${{ inputs.week }}_*.csv
    - name: Get Tokei
      run: sudo wget -qO tokei.tar.gz https://github.com/XAMPPRocky/tokei/releases/latest/download/tokei-x86_64-unknown-linux-gnu.tar.gz
    - name: Install Tokei
      run: sudo tar xf tokei.tar.gz -C /usr/local/bin
    - name: Tokei version
      run: tokei --version
    - name: Run Tokei
      run: tokei -f challenge-${{ inputs.week }} > /tmp/challenge-${{ inputs.week }}.tokei.txt
    - name: Archive Tokei report
      uses: actions/upload-artifact@v3
      with:
        name: tokei-stats-report
        path: /tmp/challenge-${{ inputs.week }}.tokei.txt
