Task1←{𝕊paragraph:
 "."∾˜{𝕨∾". "∾𝕩}´{𝕨∾' '∾𝕩}´∘(⍋∘(⊢+32×1="A["⍋⊢)⊸⊏)¨' '((⊢-˜¬×+`)∘=⊔⊢)¨ ". " ((¬-˜⊢×·+`»>⊢)∘(¬»∨⊢)∘(≠∘⊢↑⍷)⊔⊢) paragraph∾' '
}
#dd←"All he could think about was how it would all end. There was still a bit of uncertainty in the equation, but the basics were there for anyone to see. No matter how much he tried to see the positive, it wasn't anywhere to be seen. The end was coming and it wasn't going to be pretty."
#Task1 dd
