# Solution to Task 2 of The Weekly Challenge 233
# https://theweeklychallenge.org/blog/perl-weekly-challenge-233/#TASK2

# Description:
# https://andrewshitov.com/2023/09/05/sorting-numbers-in-raku-with-the-help-of-chatgpt/

# Test run:
#
# $ raku ch-2.raku
# [3 1 1 2 2 2]
# [1 3 3 2 2]
# [5 -1 4 4 -6 -6 1 1 1]

# The frequency-sort function was generated by ChatGPT (almost correctly),
# see more details in the blog linked above.

sub frequency-sort(@arr) {
    my %freq;
    %freq{$_}++ for @arr;

    my @sorted = @arr.sort: {
        %freq{$^a} <=> %freq{$^b} ||
        $^b <=> $^a
    };

    return @sorted;
}

my @tests =
    (1, 1, 2, 2, 2, 3),
    (2, 3, 1, 3, 2),
    (-1, 1, -6, 4, 5, -6, 1, 4, 1);

say frequency-sort($_) for @tests;
